# LightESB MySQL Route Service - 通用配置
# ================================================
SYSTEMID=CSIP
system.name=csip
system.version=1.0.0
system.description=MySQL路由服务

# 端口层级配置
port.level=system
server.port=9091

# 服务启动与组件加载
HTTP.Listener=false
system.components=externaldb
