# Robot gRPC gateway mock sample service config
service.name=RobotGrpcGatewaySrv
service.version=v1.0.0
service.description=Robot HTTP to gRPC gateway mock sample
service.author=LightESB Team
service.instance.id=robot-grpc-gateway-001
service.instance.name=Robot gRPC Gateway Mock Instance
service.environment=development
