# LightESB TempApprovalMockSrv - common configuration

SYSTEMID=CSIP
system.name=csip
system.version=1.0.0
system.description=Temporary approval form webpage mock service

port.level=version
server.port=19097

HTTP.Listener=true
server.running=true
system.components=undertowhttp,servicelog
